SOURCE="/"
DEST_ROOT="/mnt/b/backup/${HOSTNAME}"
# USE_PER_DIR_FILTERS=true

USE_SSH=true
SSH_KEY="/root/.ssh/id_ed25519"
SSH_USER="root"
SSH_HOST="remote-host"
# SSH_PORT=22
# SSH_HOST_IS_SOURCE=false

IS_DRY_RUN=true